/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'id' : MessageId,
  'text' : string,
  'senderName' : string,
  'roomId' : RoomId,
}
export type MessageId = bigint;
export interface NewMessage { 'text' : string, 'senderName' : string }
export type RoomId = bigint;
export interface UpdateProfile { 'username' : string, 'avatarUrl' : string }
export interface UserMetadata {
  'username' : string,
  'avatarUrl' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoEntry {
  'url' : string,
  'title' : string,
  'size' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVideo' : ActorMethod<[string, string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRoom' : ActorMethod<[], RoomId>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getAllVideosSortedBySize' : ActorMethod<[Principal], Array<VideoEntry>>,
  'getCallerProfile' : ActorMethod<[], [] | [UserMetadata]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIceCandidates' : ActorMethod<[RoomId], [] | [Array<string>]>,
  'getSdpAnswer' : ActorMethod<[RoomId], [] | [string]>,
  'getSdpOffer' : ActorMethod<[RoomId], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserMetadata]>,
  'getVideos' : ActorMethod<[Principal], Array<VideoEntry>>,
  'initializeUser' : ActorMethod<[string, [] | [string]], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<UserMetadata>>,
  'pollMessagesAfter' : ActorMethod<[MessageId, RoomId], Array<Message>>,
  'postIceCandidate' : ActorMethod<[RoomId, string], undefined>,
  'postMessage' : ActorMethod<[RoomId, NewMessage], undefined>,
  'postSdpAnswer' : ActorMethod<[RoomId, string], undefined>,
  'postSdpOffer' : ActorMethod<[RoomId, string], undefined>,
  'saveCallerProfile' : ActorMethod<[UpdateProfile], undefined>,
  'searchUsersByUsername' : ActorMethod<[string], Array<UserMetadata>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];