/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RoomId = IDL.Nat;
export const VideoEntry = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'size' : IDL.Nat,
});
export const UserMetadata = IDL.Record({
  'username' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const MessageId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'text' : IDL.Text,
  'senderName' : IDL.Text,
  'roomId' : RoomId,
});
export const NewMessage = IDL.Record({
  'text' : IDL.Text,
  'senderName' : IDL.Text,
});
export const UpdateProfile = IDL.Record({
  'username' : IDL.Text,
  'avatarUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRoom' : IDL.Func([], [RoomId], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getAllVideosSortedBySize' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VideoEntry)],
      ['query'],
    ),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(UserMetadata)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIceCandidates' : IDL.Func(
      [RoomId],
      [IDL.Opt(IDL.Vec(IDL.Text))],
      ['query'],
    ),
  'getSdpAnswer' : IDL.Func([RoomId], [IDL.Opt(IDL.Text)], ['query']),
  'getSdpOffer' : IDL.Func([RoomId], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserMetadata)],
      ['query'],
    ),
  'getVideos' : IDL.Func([IDL.Principal], [IDL.Vec(VideoEntry)], ['query']),
  'initializeUser' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserMetadata)], ['query']),
  'pollMessagesAfter' : IDL.Func(
      [MessageId, RoomId],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'postIceCandidate' : IDL.Func([RoomId, IDL.Text], [], []),
  'postMessage' : IDL.Func([RoomId, NewMessage], [], []),
  'postSdpAnswer' : IDL.Func([RoomId, IDL.Text], [], []),
  'postSdpOffer' : IDL.Func([RoomId, IDL.Text], [], []),
  'saveCallerProfile' : IDL.Func([UpdateProfile], [], []),
  'searchUsersByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserMetadata)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RoomId = IDL.Nat;
  const VideoEntry = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'size' : IDL.Nat,
  });
  const UserMetadata = IDL.Record({
    'username' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const MessageId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'text' : IDL.Text,
    'senderName' : IDL.Text,
    'roomId' : RoomId,
  });
  const NewMessage = IDL.Record({ 'text' : IDL.Text, 'senderName' : IDL.Text });
  const UpdateProfile = IDL.Record({
    'username' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRoom' : IDL.Func([], [RoomId], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getAllVideosSortedBySize' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VideoEntry)],
        ['query'],
      ),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(UserMetadata)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIceCandidates' : IDL.Func(
        [RoomId],
        [IDL.Opt(IDL.Vec(IDL.Text))],
        ['query'],
      ),
    'getSdpAnswer' : IDL.Func([RoomId], [IDL.Opt(IDL.Text)], ['query']),
    'getSdpOffer' : IDL.Func([RoomId], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserMetadata)],
        ['query'],
      ),
    'getVideos' : IDL.Func([IDL.Principal], [IDL.Vec(VideoEntry)], ['query']),
    'initializeUser' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserMetadata)], ['query']),
    'pollMessagesAfter' : IDL.Func(
        [MessageId, RoomId],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'postIceCandidate' : IDL.Func([RoomId, IDL.Text], [], []),
    'postMessage' : IDL.Func([RoomId, NewMessage], [], []),
    'postSdpAnswer' : IDL.Func([RoomId, IDL.Text], [], []),
    'postSdpOffer' : IDL.Func([RoomId, IDL.Text], [], []),
    'saveCallerProfile' : IDL.Func([UpdateProfile], [], []),
    'searchUsersByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserMetadata)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };